### ISSUE TITLE
SASS usage

### ISSUE THREAD

**Issue by iandunn** [2ndkauboy/campsite-2017#14]
It doesn't look like the SASS files are used at all. Is that right?

If so, I don't see any reason to keep them.

If they are being used, what are you using to compile them? It'd be nice to have something standard, like grunt, webpack, etc.

**Comment by 2ndkauboy** [comment]
SASS is used. Just not for the `rtl.css` file. I use the default ruby sass compiler and personally would not like to have a  grunt/gulp file in the repo.

**Comment by iandunn** [comment]
Hmmm, yeah, if it's just `$ sass sass/* style.css`, then grunt is probably overkill.
