### ISSUE TITLE
Document navigation.js switch

### ISSUE THREAD

**Issue by iandunn** [2ndkauboy/campsite-2017#16]
I'm curious why the _s navigation.js was replaced with twentyseveteen's. I think it'd be good to document that.

**Comment by 2ndkauboy** [comment]
OK, I will document in the header comment, that it's a variant of TwentySeventeen's navigation. The reason behind that was, that the _s `navigation.js` is not as keyboard accessbile as it should be. You couldn't easily navigate through submenues or not even reach them at all.
