### ISSUE TITLE
Maybe remove Speaker template

### ISSUE THREAD

**Issue by iandunn** [2ndkauboy/campsite-2017#17]
It seems like any speaker-specific content would work better as a plugin, so that it'll work for all themes, rather than us having to re-create it in each theme.

The `wc-post-types` plugin already adds links to sessions, slides, and videos, too, so I'm not sure that's necessary.

Am I missing anything?

**Comment by 2ndkauboy** [comment]
So you would rather use the `the_content` filter to add the list?

This is the content we wanted to produce: https://preview.uxpin.com/a3592af77f79363b277cc2502381a9846ac1839d#/pages/66748816/simulate/sitemap

Currently, only the Session name (linked to it's single view)  is printed on the speakers bio page. And even on the session single view, the slides and video link is not used. It's only shown on the sessions archive page.

**Comment by iandunn** [comment]
> So you would rather use the the_content filter to add the list?

Using `the_content` isn't great, but I don't see a better way if we want to apply the changes to all themes.

Actually, there have been some new templating hooks introduced in the past few WP versions. I wonder if we could move `single-wcb_speaker.php` into a plugin, and then filter something to include the path from the plugin. I'm not sure if that's possible or not. 

Related tickets:

https://core.trac.wordpress.org/ticket/13239
https://core.trac.wordpress.org/ticket/14310
https://core.trac.wordpress.org/ticket/21062
https://core.trac.wordpress.org/ticket/22355
https://core.trac.wordpress.org/ticket/27322
https://core.trac.wordpress.org/ticket/18302

Even if that is possible, though, I wonder if it'll be a problem that each theme has different surrounding markup. `the_content` might be better because it doesn't have that issue.

> This is the content we wanted to produce: 

I don't see any problem with adding any of that to the content that `wc-post-types` already outputs. We'd need to make sure we don't break back-compat with older sites, but as long as we're only adding new things, then that probably won't be an issue. We can use [feature flags](https://meta.trac.wordpress.org/browser/sites/trunk/wordcamp.org/public_html/wp-content/mu-plugins/helper-functions.php?rev=5223&marks=109-130#L107) to add things conditionally if needed.

**Comment by 2ndkauboy** [comment]
Mist if the tickets refer to the template hierarchy, which is what I used to introduce that template. I haven't seen a way in how to do it without a special page template. But I also wasn't aware, that there already is a filter to add a simple list of session. It's probably best to use this function.

I can't see any problems we might have with older WordCamp sites. If the secondary query doesn't gets any sessions, nothing will be printed. But as the current filer also queries for sessions, just with fewer fields,that should be fine.

So could we possibly have that addition added to the plugin together with the theme? Or do you want me to write a meta blog post with the idea first?

**Comment by iandunn** [comment]
I don't think it needs an additional feature request post on make/Community, since the theme itself was already approved. This is more of an implementation detail.

It will need a Meta ticket and patch, though.

**Comment by 2ndkauboy** [comment]
OK, I'll prepare one. And thanks for the commit of the theme. Do you know, how soon it will get updated?

**Comment by 2ndkauboy** [comment]
Here is the patch with the changes: https://meta.trac.wordpress.org/ticket/2849

**Comment by iandunn** [comment]
Thanks!
