### ISSUE TITLE
Menu toggle not working?

### ISSUE THREAD

**Issue by iandunn** [2ndkauboy/campsite-2017#20]
It doesn't look like the responsive menu toggling is working, unless I've messed something up locally :)

It seems like maybe a difference between the `toggled` and `toggled-on` attributes in _s vs TwentySeventeen, but I haven't looked closely.

**Comment by 2ndkauboy** [comment]
Seems you are right. In the styles it should be `toggled-on` 🙈

**Comment by iandunn** [comment]
I won't have time to look closely until tomorrow, but I'm still not seeing the button show up on small screens. Am I missing something?

**Comment by iandunn** [comment]
Looks good now, thanks!
