### ISSUE TITLE
Sketch design export

### ISSUE THREAD

**Issue by marcustisater** [2ndkauboy/campsite-2017#22]
Is it possible to get the Sketch/Photoshop export of the design? Awesome work btw 🎉 🍾

**Comment by 2ndkauboy** [comment]
Hi @marcustisater. Thanks for your nice words. But unfortunately, there is not "design" we could export. The theme itself has almost no design., It's just some bare Underscores with some special improvements for WordCamps.

Which design are you referring to? Maybe the one shown on the blog post about the style guide?

**Comment by marcustisater** [comment]
I understand, no worries. Keep up the good work!

**Comment by 2ndkauboy** [comment]
If you want to use our theme, check out the Style Guide from @lucijanblagonic: https://github.com/lucijanblagonic/wceu-2017
