### ISSUE TITLE
Scroll menu into view when opening

### ISSUE THREAD

**Issue by kraftner** [2ndkauboy/campsite-2017#24]
Today I got the feedback for our site https://2019.vienna.wordcamp.org/ that if you toggle the menu open on mobile and coincidently your screen height makes it so that the menu toggle button aligns with the bottom of the screen you have hardly any feedback that anything happened.

I was wondering if that is a known thing and/or intentional (Not sure how great it is to scroll things around with regards to a11y) or something that could be improved.

**Comment by 2ndkauboy** [comment]
Hi @kraftner, sorry that I haven't got back earlier. The alignment of the menu is based on the CSS you apply. The theme itself has very little CSS bundles with it. And it is usually replaced with the Remote CSS functionality of the WordCamp.org website.

In terms of a11y, the theme is using the `aria-expanded` attribute, which is toggled together with the menu. So a screen reader user should be informed about the change on the website.

As the menu also has an "arrow indicator" even if the screen does not scroll, a user should recognize, that something happened.

As for the Vienna website, I would suggest to either reduce the image size or to place the menu absolute on top of the screen as an alternative.
