### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by coreymckrill** [2ndkauboy/campsite-2017#4]
- [x] **functions.php:46** - Combine the two `register_nav_menus()` calls into one
- [x] **functions.php:379** - Since this isn't a child theme, why use `get_parent_theme_file_path()` instead of `get_theme_file_path()`?
- [x] **comments.php:31** - `gettext` call containing placeholders is not accompanied by "translators:" comment.
- [x] **comments.php:31** - Singular placeholder is missing, which is needed for some languages. https://codex.wordpress.org/I18n_for_WordPress_Developers#Plurals
- [x] **content-day-of.php:3** - has wrong template name in file header
- [x] If there are functions that are copied over from something other than _s (e.g. Twenty Seventeen), that should be noted in the doc block for the function, including the version of the theme it's copied from.

**Comment by 2ndkauboy** [comment]
Thanks for the good hint about copied functions. I will try to work on all issues till the weekend.

**Comment by 2ndkauboy** [comment]
@coreymckrill is there a standard way to reference the origin of a function? I haven't found something in the PHPDoc tags list.

**Comment by 2ndkauboy** [comment]
I also basically copied the whole `inc/icon-functions.php` file. Would you says it's enough to note that in the file header?

**Comment by coreymckrill** [comment]
I'm not aware of a standard PHPDoc tag for function origin. I usually just add it on a separate line of the function description.

> I also basically copied the whole `inc/icon-functions.php` file. Would you says it's enough to note that in the file header?

Yeah, I think that would be sufficient, but in that case, I would also note in the individual function docs where you've made changes from the original file.

**Comment by 2ndkauboy** [comment]
Could you give me an example on how and where you do it? Just that I make it correctly :)

**Comment by 2ndkauboy** [comment]
It looks like the pluralization does work for languages such as russian. I tested it with 21 comments and it showed the correct number. Although there is an old PR on _s addressing this "issue": https://github.com/Automattic/_s/pull/1012

**Comment by 2ndkauboy** [comment]
@coreymckrill are you sure **comments.php:31** is really an issue? The string is the default as found in _s. I am also quite sure, that it's not an issue, if in the default English string, the placeholder is missing. In other languages it can still be used, as far as I know. But I just copied the current version from TwentySeventeen, as I am quite sure the issue will finally be solved in _s as well.

**Comment by coreymckrill** [comment]
> Could you give me an example on how and where you do it? Just that I make it correctly :)

I'm having trouble at the moment finding other examples in the Meta codebase. But here's how I would do it:

```php
<?php
/**
 * SVG icons related functions and filters
 *
 * This file is largely copied from version x.x.x of [origin]. Changes to individual
 * functions are noted in their doc blocks.
 *
 * @package CampSite_2017
 * @since 1.0
 */
```

And then for a function, something like:

```php
/**
 * Return SVG markup.
 *
 * Modified from [origin] to remove usage error messages.
 *
 * @param array $args {
 *     Parameters needed to display an SVG.
 *
 *     @type string $icon  Required SVG icon filename.
 *     @type string $title Optional SVG title.
 *     @type string $desc  Optional SVG description.
 * }
 * @return string SVG markup.
 */
```

**Comment by coreymckrill** [comment]
> are you sure comments.php:31 is really an issue?

I was alerted to it by WPCS running on my IDE. It certainly is minor, but given that A) it's particularly important for us to have good i18n on WordCamp sites, and B) there is an active PR in the **_s** repo to fix this, I think it should be fixed here as well.

Could probably just copy the PR from **_s**.
