### ISSUE TITLE
What's the purpose of having both a "Full-Width" and a "No Sidebar" page template?

### ISSUE THREAD

**Issue by coreymckrill** [2ndkauboy/campsite-2017#5]
These seem to be identical other than a class on the primary container. Are they both needed?

**Comment by 2ndkauboy** [comment]
Do you have an idea on how to solve it differently? The idea behind:
- No sidebar: centered content without a sidebar but not 100% width (for better readability)
- Full width: as before, but with 100% width (useful for pages such as schedule)

You can find them on our mockups (although the full width has text here): https://preview.uxpin.com/a3592af77f79363b277cc2502381a9846ac1839d#/pages/66748832/simulate/sitemap

**Comment by coreymckrill** [comment]
Per our Slack chat, I can now see the purpose of having separate templates. Note, though, that since the theme does not come with any styles, this will not be evident to site designers unless they look at those particular sections of the accompanying style guide (which they hopefully will).

**Comment by iandunn** [comment]
Does it seem like the average site will want to use both of those templates at the same time? I would guess not, but I could be wrong.

If not, then it seems like we could just have a single `No Sidebar` template, and let them define the content width they want in CSS.

**Comment by 2ndkauboy** [comment]
Pages with full width are harder to read, if the text has the full width. That was about reason behind having a separate page template. Without it, the designer has to use the body classes with the slug if the page, which would introduce issues when pages are renamed. I think it doesn't hurt to have both, but if you disagree, I would keep the `No Sidebar` template.
